# Generated by Django 5.2.4 on 2025-08-04 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitcard',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='debitcard',
            name='guest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='guest_house.guest'),
        ),
        migrations.AddField(
            model_name='debitcard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='debitcard',
            name='cvc',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
