# Generated by Django 5.2.4 on 2025-08-18 00:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_house', '0002_debitcard_cardholder_name_debitcard_guest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
